defaults: &defaults
  host: "localhost"
  port: 4444
  browser: "*firefox"
  base_url: "http://www.gm.ca"
  timeout: 20

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults

